### ISSUE TITLE
Variable from drakma package still being referenced. 

### ISSUE THREAD

**Issue by jolby** [lisp-maintainers/quicksearch#1]
https://github.com/lisp-maintainers/quicksearch/blob/2134cdc151bdc7cb3c2c8c8e7bb2ec7e1636a912/quicksearch.lisp#L199

This causes build errors (for me at least) when building quicksearch and transitively, CIEL.

**Comment by vindarel** [comment]
Thanks for the report.

FYI my CIEL builds are still using https://github.com/tkych/quicksearch (but there's no reason to)
